import uuid
from types import NotImplementedType


class UUID(uuid.UUID):
    """A C-backed UUID value constructed from canonical text or 16 bytes."""

    def __init__(self, inp: str | bytes) -> None: ...
    @property
    def bytes(self) -> bytes: ...
    @property
    def bytes_le(self) -> bytes: ...
    @property
    def int(self) -> int: ...
    @property
    def hex(self) -> str: ...
    @property
    def fields(self) -> tuple[int, int, int, int, int, int]: ...
    @property
    def time_low(self) -> int: ...
    @property
    def time_mid(self) -> int: ...
    @property
    def time_hi_version(self) -> int: ...
    @property
    def clock_seq_hi_variant(self) -> int: ...
    @property
    def clock_seq_low(self) -> int: ...
    @property
    def time(self) -> int: ...
    @property
    def clock_seq(self) -> int: ...
    @property
    def node(self) -> int: ...
    @property
    def urn(self) -> str: ...
    @property
    def variant(self) -> str: ...
    @property
    def version(self) -> int | None: ...
    @property
    def is_safe(self) -> uuid.SafeUUID: ...
    def __str__(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[type[UUID], tuple[bytes]]: ...
    def __eq__(self, other: object) -> bool | NotImplementedType: ...
    def __ne__(self, other: object) -> bool | NotImplementedType: ...
    def __lt__(self, other: object) -> bool | NotImplementedType: ...
    def __gt__(self, other: object) -> bool | NotImplementedType: ...
    def __le__(self, other: object) -> bool | NotImplementedType: ...
    def __ge__(self, other: object) -> bool | NotImplementedType: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...


def uuid4_bytes() -> bytes:
    """Return 16 random bytes with UUID v4 and RFC variant bits set."""
    ...


def uuid4() -> UUID:
    """Return a random version 4 UUID."""
    ...
